### ISSUE TITLE
Create snapshot error : Additional properties are not allowed (u'display_description' was unexpected)

### ISSUE THREAD

**Issue by haibowu323** [openstack4j/openstack4j#152]
https://github.com/openstack4j/openstack4j/blob/670446a7d3b3c8f29efa9ca5f8e76496007cbddd/core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolumeSnapshot.java#L192

**When create a snapshot by use CinderVolumeSnapshot class and set description,it will causea error**

org.openstack4j.api.exceptions.ClientResponseException: Invalid input for field/attribute snapshot. Value: {u'display_name': u'aP2Uk2', u'name': u'aP2Uk2', u'description': u'aP2Uk2', u'display_description': u'aP2Uk2', u'volume_id': u'7adb3a1b-85e3-4dc8-b765-7d76ed79d711', u'metadata': {u'display_description': u'aP2Uk2'}}. Additional properties are not allowed (u'display_description' was unexpected)
	at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:58) ~[openstack4j-3.9.jar:?]
	at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:70) ~[openstack4j-3.9.jar:?]
	at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:99) ~[openstack4j-3.9.jar:?]
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:45) ~[openstack4j-3.9.jar:?]
	at org.openstack4j.connectors.resteasy.HttpResponseImpl.getEntity(HttpResponseImpl.java:63) ~[openstack4j-resteasy-3.9.jar:?]
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:248) ~[openstack4j-3.9.jar:?]
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:238) ~[openstack4j-3.9.jar:?]
	at org.openstack4j.openstack.storage.block.internal.BlockVolumeSnapshotServiceImpl.create(BlockVolumeSnapshotServiceImpl.java:78) ~[openstack4j-3.9.jar:?]

**In Cinder train project's source code-cinder/api/schemas/snapshots.py,it difine create snapshot parameter schema:**
create = {
    'type': 'object',
    'properties': {
        'type': 'object',
        'snapshot': {
            'type': 'object',
            'properties': {
                'name': parameter_types.name_allow_zero_min_length,
                'display_name': parameter_types.name_allow_zero_min_length,
                'description': parameter_types.description,
                'volume_id': parameter_types.uuid_allow_null,
                'force': parameter_types.boolean,
                'metadata': parameter_types.metadata_allows_null,
            },
            'required': ['volume_id'],
            'additionalProperties': False,
        },
    },
    'required': ['snapshot'],
    'additionalProperties': False,
}
I want to know why set 'display_description' in CinderVolumeSnapshot ,thank you.

**Comment by yylike-new** [comment]
yes，I have the same problem. And I tried using the cinder cli with “description” .   
$ cinder snapshot-create --description try <volume>  
succeed

so I want to know why？And have you solved the problem？
thank you.

**Comment by yssCheng** [comment]
error message：
Invalid input for field/attribute snapshot. Value: {'name': 'test-001', 'display_name': 'test-001', 'description': 'est', 'display_description': 'test', 'volume_id': '9ba06857-ceb5-44dc-95f9-86be6c661975'}. Additional properties are not allowed ('display_description' was unexpected)

I have the same problem. 

have you solved the problem？thank you.
