### ISSUE TITLE
Not able to connect to openstack version stein with OS_AUTH_URL https://<fqdn>/identity/v3

### ISSUE THREAD

**Issue by Dhanusha-Jeevan** [openstack4j/openstack4j#154]
Hi,

using openstack4j version 3.2.0 and able to connect to openstack infra with OS_AUTH_URL format https://<fqdn>:<port>/v3,
but not able to connect to OS_AUTH_URL https://<fqdn>/identity/v3

os = OSFactory.builderV3().endpoint("https://<fqdn/identity/v3").credentials(<username>,<password>, Identifier.byName("Default")).scopeToProject(Identifier.byId(<project_id>)).authenticate();

failing with error
```
Exception in thread "main" AuthenticationException{message=Unauthorized, status=401}
        at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:36)
        at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
        at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV3(OSAuthenticator.java:191)
        at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:74)
        at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:172)
        at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:129)
```

Thanks in advance. 

Regards,
Dhanusha

**Comment by ybbidrngj** [comment]
I meet same issue.Did you solve it?
