### ISSUE TITLE
Unable to create port allowed pairs

### ISSUE THREAD

**Issue by alvidic** [openstack4j/openstack4j#160]
Adding allowed pairs to existing port fails when using:
os.networking().port().update(port.toBuilder().allowedAddressPair(ip, port.getMacAddress()).build());

**NOTE: Method works fine in version 3.7**

## Current Behavior

Flow:
- create port
`os.networking().port().create(portBuilder.build());`
- create server
`os.compute().servers() .bootAndWaitActive(serverCreate, ..)`
- find port (to get mac)
`os.networking().port().list()`
- add allowed pairs to created port
`os.networking().port().update(port.toBuilder().allowedAddressPair(ip, port.getMacAddress()).build());`
Allowed pairs fails with:
`
ClientResponseException{message=Cannot update read-only attribute updated_at, status=400, status-code=BAD_REQUEST, X-Openstack-Request-Id=req-b92c2e45-1208-45b1-8d3d-4c3a6d1acddb}
	at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:58)
	at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:70)
	at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:99)
	at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:45)
	at org.openstack4j.connectors.resteasy.HttpResponseImpl.getEntity(HttpResponseImpl.java:63)
...
`

By turning on detailed wire log came up with next difference in body (between v3.7 and v3.10):
- **v3.7 (working fine)**

PUT /v2.0/ports/... HTTP/1.1
...
{
"port" : {[\n]"
"name" : "_PORT_NAME_",[\n]"
"admin_state_up" : true,[\n]"
"device_id" : "_DEVICE_ID_",[\n]"
"device_owner" : "compute:nova",[\n]"
"fixed_ips" : [ {[\n]"
"      "ip_address" : "172.59.208.237",[\n]"
"      "subnet_id" : "bddc8b8e-0861-4764-9cb2-cf5bece802e2"[\n]"
"    } ],[\n]"
"    "allowed_address_pairs" : [ {[\n]"
"      "ip_address" : "172.59.208.238",[\n]"
"      "mac_address" : "dc:16:3e:7a:9b:db"[\n]"
"    } ],[\n]"
"    "security_groups" : [ "95faecda-3f32-4d0c-b1e9-5b58cfb68eec" ],[\n]"
"    "extra_dhcp_opts" : [ ],[\n]"
"    "port_security_enabled" : true,[\n]"
"    "binding:host_id" : "cloudims12-node5.iskratel.mak",[\n]"
"    "binding:vnic_type" : "normal",[\n]"
"    "binding:profile" : { }[\n]"
"  }[\n]"
"}"

Response: HTTP/1.1 200 OK

- **v3.10 (fails)**

PUT /v2.0/ports/...HTTP/1.1
...
{
"port" : {[\n]"
"name" : "_PORT_NAME_",[\n]"
"admin_state_up" : true,[\n]"
"device_id" : "_DEVICE_ID_",[\n]"
"device_owner" : "compute:nova",[\n]"
"fixed_ips" : [ {[\n]"
"      "ip_address" : "172.59.208.237",[\n]"
"      "subnet_id" : "bddc8b8e-0861-4764-9cb2-cf5bece802e2"[\n]"
"    } ],[\n]"
"    "allowed_address_pairs" : [ {[\n]"
"      "ip_address" : "172.59.208.238",[\n]"
"      "mac_address" : "dc:16:3e:7a:9b:db"[\n]"
"    } ],[\n]"
"    "security_groups" : [ "95faecda-3f32-4d0c-b1e9-5b58cfb68eec" ],[\n]"
"    "extra_dhcp_opts" : [ ],[\n]"
"    "port_security_enabled" : true,[\n]"
"    "binding:host_id" : "cloudims12-node5.iskratel.mak",[\n]"
"    "binding:vnic_type" : "normal",[\n]"
"    "binding:profile" : { }[\n]"
**"    "created_at" : 1631269251000,[\n]"
"    "updated_at" : 1631514315000[\n]"**
"  }[\n]"
"}"

Response: HTTP/1.1 400 Bad Request

## Expected Behavior

Successfully created allowed pair:

(openstack) port show -c allowed_address_pairs -c fixed_ips _PORT_NAME_
+-----------------------+--------------------------------------------------------------+
| Field                     | Value                                                                      |
+-----------------------+--------------------------------------------------------------+
| allowed_address_pairs | ip_address='172.59.208.238', mac_address='dc:16:3e:7a:9b:db' |
| fixed_ips             | ip_address='172.59.208.237', subnet_id='bddc8b8e-0861-4764-9cb2-cf5bece802e2' |
+-----------------------+--------------------------------------------------------------+

## Environment

Openstack driver:
`dependencies {
    compile group: 'com.github.openstack4j.core', name: 'openstack4j', version: '3.10'
}`
Openstack version: 
`Rocky`

**Comment by bboyHan** [comment]
Thank you for your feedback.

**Comment by olivergondza** [comment]
> Seems like fields created_at and/or updated_at are cause of the problem...

Correct, these are obtained, but should not be sent.

**Comment by saschariedel** [comment]
Hi, any news on this? This bug is opened since Nov 2021....

**Comment by tangguochang** [comment]
any one planning fix this ?

**Comment by alvidic** [comment]
I did a liitle digin and seems like problem causes interface `org.openstack4j.model.network.Port`, when it extends `TimeEntity`. 
This appends `createdTime `and `updatedTime` in request.

I pull code and remove this extend clause (and with changes in implementing `org.openstack4j.openstack.networking.domain.NeutronPort`) and then things go right.

Here is my test case:

```java
public void testAddAllowedPairs() throws Exception {
    // authenticate
    final OSClient os = OSD.authenticate(VIM_INSTANCE);
    String netId = "3a42c640-c76c-456f-825f-c5f6f1a04f44";
    String serverFixedIp = "172.29.6.12";
    String allowedAddress = "172.29.7.210";
    try {
      // get all ports on dedicated network
      List<? extends Port> myports =
          os.networking().port().list(PortListOptions.create().networkId(netId));
      // find my port
      Optional<? extends Port> myoport =
          myports.stream()
              .filter(
                  p -> {
                    Optional o =
                        p.getFixedIps().stream()
                            .filter(a -> a.getIpAddress().equals(serverFixedIp))
                            .findAny();
                    return o.isPresent();
                  })
              .findFirst();
      if (myoport.isPresent()) {
        // assign allowed pair
        Port myport = myoport.get();
        os.networking()
            .port()
            .update(
                myport
                    .toBuilder()
                    .allowedAddressPair(allowedAddress, myport.getMacAddress())
                    .build());
      } else {
        System.out.println("? NOT FOUND");
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
```

**Comment by alvidic** [comment]
I did a little digin and seems like problem causes interface `org.openstack4j.model.network.Port` when it extends `TimeEntity`. This extension appends `createTime` and `updateTime` into request.  
I pull down code and remove this extension (+ small changes in implementig class `org.openstack4j.openstack.networking.domain.NeutronPort`). After that, **things turns into right direction**.

Here is my test case:

```java
public void testAddAllowedPairs() throws Exception {
    // authenticate
    final OSClient os = OSD.authenticate(VIM_INSTANCE);

    String netId = "3a42c640-c76c-456f-825f-c5f6f1a04f44";
    String serverFixedIp = "172.29.6.12";
    String allowedAddress = "172.29.7.210";
    try {
      // get ports from my dedicated neteork
      List<? extends Port> myports =
          os.networking()
            .port()
            .list(PortListOptions.create()
              .networkId(netId));
      // find my port
      Optional<? extends Port> myoport =
          myports.stream()
              .filter(
                  p -> {
                    Optional o =
                        p.getFixedIps().stream()
                            .filter(a -> a.getIpAddress().equals(serverFixedIp))
                            .findAny();
                    return o.isPresent();
                  })
              .findFirst();
      if (myoport.isPresent()) {
        // assign allowed pair
        Port myport = myoport.get();
        os.networking()
            .port()
            .update(
                myport
                    .toBuilder()
                    .allowedAddressPair(allowedAddress, myport.getMacAddress())
                    .build());
      } else {
        System.out.println("? NOT FOUND");
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
```
