### ISSUE TITLE
FloatingIPService.disassociateFromPort(fipId) doesn't work

### ISSUE THREAD

**Issue by ABNikola** [openstack4j/openstack4j#191]
I'm trying to use 

os.networking().floatingip().disassociateFromPort(floatingId);

and I see in log

[DEBUG] Executing Request: PUT https://cloud.sever.com:9696/v2.0/floatingips/6a4143f9-db79-45cc-87f5-d4c17687e192

## Current Behavior

But I get

DEBUG: - Interceptor Context: org.jboss.resteasy.core.interception.ClientWriterInterceptorContext,  Method : proceed
DEBUG: - RESTEASY004672: Client send processing failure.
javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/json type: java.lang.String
	at org.jboss.resteasy.core.interception.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:38)
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:146)
	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:121)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:399)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.writeRequestBodyToOutputStream(ApacheHttpClient4Engine.java:673)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.buildEntity(ApacheHttpClient4Engine.java:638)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.loadHttpMethod(ApacheHttpClient4Engine.java:516)
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:315)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:443)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:63)
	at org.openstack4j.connectors.resteasy.HttpCommand.execute(HttpCommand.java:70)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invokeRequest(HttpExecutorServiceImpl.java:60)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.invoke(HttpExecutorServiceImpl.java:53)
	at org.openstack4j.connectors.resteasy.HttpExecutorServiceImpl.execute(HttpExecutorServiceImpl.java:31)
	at org.openstack4j.core.transport.internal.HttpExecutor.execute(HttpExecutor.java:54)
	at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:244)
	at org.openstack4j.openstack.networking.internal.FloatingIPServiceImpl.disassociateFromPort(FloatingIPServiceImpl.java:97)

## Expected Behavior

I should not receive errors, and this method should work correctly.

## Environment

I use in pom.xml

```
<dependency>
    <groupId>com.github.openstack4j.core</groupId>
    <artifactId>openstack4j</artifactId>
    <version>3.10</version>
</dependency>
```

Java SDK 1.8.0_291

OpenStack version: 2.88

## Impact

In old code I use 

os.compute().floatingIps().removeFloatingIP(serverId, ip);

It works correct, but it's deprecated. And I need to change it.

**Comment by ABNikola** [comment]
```
package org.openstack4j.core.transport;
public class HttpRequest<R> {
034:	String json;

package org.openstack4j.connectors.resteasy;
public final class HttpCommand<R> {
    public Response execute() {

        } else if (request.hasJson()) {
065:         webRequest = resteasyRequest.build(request.getMethod().name(), Entity.entity(request.getJson(), ClientConstants.CONTENT_TYPE_JSON));
```
You write ClientConstants.CONTENT_TYPE_JSON) and wait for JSON , but request.getJson() returns String because of HttpRequest.json is String. Maybe you should return JSON in request.getJson().

**Comment by ABNikola** [comment]
I found a solution. Since Resteasy requires Javaee, I exclude it and connect it httpclient

```
        <dependency>
            <groupId>com.github.openstack4j.core</groupId>
            <artifactId>openstack4j</artifactId>
            <version>3.10</version>
            <exclusions>
                <exclusion>
                    <groupId>com.github.openstack4j.core.connectors</groupId>
                    <artifactId>openstack4j-resteasy</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.github.openstack4j.core.connectors</groupId>
                    <artifactId>openstack4j-http-connector</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.github.openstack4j.core.connectors</groupId>
                    <artifactId>openstack4j-jersey2</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.github.openstack4j.core.connectors</groupId>
                    <artifactId>openstack4j-connectors</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.github.openstack4j.core.connectors</groupId>
                    <artifactId>openstack4j-httpclient</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.github.openstack4j.core.connectors</groupId>
                    <artifactId>openstack4j-okhttp</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.github.openstack4j.core</groupId>
            <artifactId>openstack4j-httpclient</artifactId>
            <version>3.10_modified.1</version>
        </dependency>

```
