### ISSUE TITLE
Assigning allowedaddresspair to port is failing with openstack4j library

### ISSUE THREAD

**Issue by sachin234s** [openstack4j/openstack4j#234]
## Current Behavior

We are using openstack4j-core-3.10.jar to call openstack api's. We are facing below issue when trying to associate allowedaddresspair to created port
```
2024-10-17 13:26:06,174 ERROR [com.hp.usage.vnfm.lcm.workflow.task.InstantiateVdu] [ThreadPoolOperationExecutorService-Thread-6] InstantiateVdu has failed. Cannot update read-only attribute created_at
org.openstack4j.api.exceptions.ClientResponseException: Cannot update read-only attribute created_at
        at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:58)
        at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:70)
        at org.openstack4j.core.transport.HttpEntityHandler.handleLessThan500(HttpEntityHandler.java:99)
        at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:45)
        at org.openstack4j.connectors.okhttp.HttpResponseImpl.getEntity(HttpResponseImpl.java:65)
        at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:248)
        at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:238)
        at org.openstack4j.openstack.networking.internal.PortServiceImpl.update(PortServiceImpl.java:89)
        at com.hp.usage.vnfm.vim.openstack.OpenStackNeutron.processPortCreation(OpenStackNeutron.java:1548)
```

## Expected Behavior
Allowed address pair should be associated with the fixed ip port

## Environment

openstack version : RHOSP 16
JDK version :openjdk 11/17
Rhel version : 8.x upwards

this usecase seemed to work earlier

## Impact

Through our vnfm application which used openstack4j lib to invoke openstack api s , we are unable to link Allowed address pair  with the fixed ip port, impacting our ops

## Steps to Reproduce

The steps to recreate are as below

1. Create vip port from allowedaddresspairs defined is successful
2. create fixed ip port is successful
3. above issue is observed when fixedipaddress is updated by passing allowed address pairs in update.

**Comment by alvidic** [comment]
Similar as #160.
Any plan to fix?
