### ISSUE TITLE
[Bug] Unkown Field in KeystoneProject

### ISSUE THREAD

**Issue by LmV4corbeau** [openstack4j/openstack4j#33]
Why when trying to get the projects i am getting the following exception:
Error logs:
```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_OBJECT token
```
```
org.openstack4j.openstack.identity.v3.domain.KeystoneProject$Projects["projects"]->java.util.ArrayList[0]->org.openstack4j.openstack.identity.v3.domain.KeystoneProject["options"])
```

Tempurary solution could be:
Add "options" to Json Annotation in class org.openstack4j.openstack.identity.v3.domain.KeystoneProject
 * Origin:
 ```
@JsonIgnoreProperties(value = "options" , ignoreUnknown = true)
 ```
 * fix
 ```
@JsonIgnoreProperties(value = {"extra", "options"} , ignoreUnknown = true)
 ```

**Comment by olivergondza** [comment]
Thanks for the report. Please attach the whole exception, code that you are invoking and ideally even the JSON payload that is being server from openstack (`OSFactory.enableHttpLoggingFilter(true)`).

**Comment by LmV4corbeau** [comment]
I can provide the Json Payload via curl
```
curl -v -s -X GET -H "X-Auth-Token: "$OS_TOKEN -H "Content-Type: application/json" "http://xxx.xxx.xxx.xxx:5000/v3/projects/5a76302425664ada86fdb55d79acab6b" | jq .
*   Trying xxx.xxx.xxx.xxx:5000...
* TCP_NODELAY set
* Connected to xxx.xxx.xxx.xxx (xxx.xxx.xxx.xxx) port 5000 (#0)
> GET /v3/projects/5a76302425664ada86fdb55d79acab6b HTTP/1.1
> Host: xxx.xxx.xxx.xxx:5000
> User-Agent: curl/7.68.0
> Accept: */*
> X-Auth-Token: gAAAAABeXldnBJ2sxbDEyhgPv6gO0yFnKdbCvxrVdNynyBbOomf6_TIybWo0dE7DwDyC3BGvMah9tADrsGfZrtjjHTEFe_EMqX47m2WJd-mJ1sqfzW3sMcfCkfdq7jAKTS3HRYlp4ZFz4j-bLx7Iaf7xqWV3qnMmY20LABFpngqnzdwy611qves
> Content-Type: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 03 Mar 2020 13:11:23 GMT
< Server: Apache
< Vary: X-Auth-Token,Accept-Encoding
< x-openstack-request-id: req-e64b0de9-d78b-445f-ace8-116040fe423e
< Content-Length: 332
< Content-Type: application/json
< 
{ [332 bytes data]
* Connection #0 to host xxx.xxx.xxx.xxx left intact
{
  "project": {
    "is_domain": false,
    "description": "Project zum Debugen von OS4j",
    "links": {
      "self": "http://127.0.0.1:5000/v3/projects/5a76302425664ada86fdb55d79acab6b"
    },
    "tags": [],
    "domain_id": "default",
    "enabled": true,
    "options": {},
    "parent_id": "default",
    "id": "5a76302425664ada86fdb55d79acab6b",
    "name": "Aurora-DebugOS4j"
  }
}
```

**Comment by LmV4corbeau** [comment]
The full Exception
```
ClientResponseException{message=Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (org.apache.http.client.entity.LazyDecompressingInputStream); line: 1, column: 350] (through reference chain: org.openstack4j.openstack.identity.v3.domain.KeystoneProject$Projects["projects"]->java.util.ArrayList[0]->org.openstack4j.openstack.identity.v3.domain.KeystoneProject["options"]), status=0, status-code=CODE_UNKNOWN}
        at org.openstack4j.connectors.httpclient.HttpResponseImpl.readEntity(HttpResponseImpl.java:137)
        at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:66)
        at org.openstack4j.connectors.httpclient.HttpResponseImpl.getEntity(HttpResponseImpl.java:67)
        at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:225)
        at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:207)
        at org.openstack4j.openstack.identity.v3.internal.ProjectServiceImpl.list(ProjectServiceImpl.java:64)
        at com.example.cluster.OSClusterConnector.listProjects(OSClusterConnector.scala:305)
        at com.example.cluster.OSClusterConnector.$anonfun$projects$1(OSClusterConnector.scala:181)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (org.apache.http.client.entity.LazyDecompressingInputStream); line: 1, column: 350] (through reference chain: org.openstack4j.openstack.identity.v3.domain.KeystoneProject$Projects["projects"]->java.util.ArrayList[0]->org.openstack4j.openstack.identity.v3.domain.KeystoneProject["options"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1216)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1126)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:63)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:10)
        at com.fasterxml.jackson.databind.deser.SettableAnyProperty.deserialize(SettableAnyProperty.java:153)
        at com.fasterxml.jackson.databind.deser.SettableAnyProperty.deserializeAndSet(SettableAnyProperty.java:134)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1564)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1228)
        at org.openstack4j.connectors.httpclient.HttpResponseImpl.readEntity(HttpResponseImpl.java:134)
        ... 19 more
```

**Comment by manuelmazzuola** [comment]
I really don't know why you got the `options` field.
I cannot find that field on the internet for the project api.
An bug on openstack?

**Comment by LmV4corbeau** [comment]
That's my guess at the moment. With the work-around you could use openstack4j with openstack train.

**Comment by manuelmazzuola** [comment]
Or a non-documented train feature.

**Comment by klonhj2015** [comment]
The api return json:{"links": {"self": "http://127.0.0.1:5000/v3/projects", "previous": null, "next": null}, "projects": [{"is_domain": false, "description": "Tenant for the openstack services", "links": {"self": "http://127.0.0.1:5000/v3/projects/10b40033bbef48f89fe838fef62398f0"}, "tags": [], "enabled": true, "id": "10b40033bbef48f89fe838fef62398f0", "parent_id": "default", "options": {}, "domain_id": "default", "name": "services"}, {"is_domain": false, "description": "default tenant", "links": {"self": "http://127.0.0.1:5000/v3/projects/600905d353a84b20b644d2fe55a21e8a"}, "tags": [], "enabled": true, "id": "600905d353a84b20b644d2fe55a21e8a", "parent_id": "default", "options": {}, "domain_id": "default", "name": "demo"}, {"is_domain": false, "description": "admin tenant", "links": {"self": "http://127.0.0.1:5000/v3/projects/8519dba9f4594f0f87071c87784a8d2c"}, "tags": [], "enabled": true, "id": "8519dba9f4594f0f87071c87784a8d2c", "parent_id": "default", "options": {}, "domain_id": "default", "name": "admin"}]}
So we can add @JsonIgnoreProperties annotation to resolve it.

**Comment by olivergondza** [comment]
This API extension went into version 16 (not sure why it is not documented):

- https://bugs.launchpad.net/keystone/+bug/1807751
- https://github.com/openstack/keystone/commit/b31ff3f991d16968db65373f3096c8cacb84219b

Note the class already have `@JsonIgnoreProperties(ignoreUnknown = true)` so unknown `options` field in input should be handled silently (I also believe adding it as `value` would not help as that ignores class _fields_, not content of the input). I presume the problem is the `@JsonAnySetter`, that feeds the `extra` field with unknown data, is set to only accept `String` values and it obviously chokes on json object (`START_OBJECT`).

@LmV4corbeau, @klonhj2015, can you please provide me with payloads from `/v3/roles` and `/v3/domains` I can use in tests? To the best of my understanding these and only these three "objects" should be affected.

**Comment by LmV4corbeau** [comment]
@olivergondza 
here is the output you ask for:

`/v3/roles`:
```
curl -v -s -X GET -H "X-Auth-Token: "$OS_TOKEN -H "Accept: application/json" -H "Content-Type: application/json" http://xxx.xxx.xxx.xxx:5000/v3/roles\?limit\=500 | jq .       

{
  "links": {
    "self": "http://127.0.0.1:5000/v3/roles?limit=500",
    "previous": null,
    "next": null
  },
  "roles": [
    {
      "description": null,
      "links": {
        "self": "http://127.0.0.1:5000/v3/roles/08597a07c6d14d378cd0d6708c20e5fe"
      },
      "options": {},
      "id": "08597a07c6d14d378cd0d6708c20e5fe",
      "domain_id": null,
      "name": "reader"
    },
    {
      "description": null,
      "links": {
        "self": "http://127.0.0.1:5000/v3/roles/2149cfabf0f44c5bbad249b1a38a625e"
      },
      "options": {},
      "id": "2149cfabf0f44c5bbad249b1a38a625e",
      "domain_id": null,
      "name": "member"
    },
    {
      "description": null,
      "links": {
        "self": "http://127.0.0.1:5000/v3/roles/790bcad86d7346cd91a7516e7bec8959"
      },
      "options": {},
      "id": "790bcad86d7346cd91a7516e7bec8959",
      "domain_id": null,
      "name": "ResellerAdmin"
    },
    {
      "description": null,
      "links": {
        "self": "http://127.0.0.1:5000/v3/roles/832e442d00434cea84195f7df09bb1bb"
      },
      "options": {},
      "id": "832e442d00434cea84195f7df09bb1bb",
      "domain_id": null,
      "name": "SwiftOperator"
    },
    {
      "description": null,
      "links": {
        "self": "http://127.0.0.1:5000/v3/roles/e3fee47e88114d6f9a8e37916ab45fcf"
      },
      "options": {},
      "id": "e3fee47e88114d6f9a8e37916ab45fcf",
      "domain_id": null,
      "name": "_member_"
    },
    {
      "description": null,
      "links": {
        "self": "http://127.0.0.1:5000/v3/roles/f768cc1132a649e7840b6d14f21d0bd8"
      },
      "options": {},
      "id": "f768cc1132a649e7840b6d14f21d0bd8",
      "domain_id": null,
      "name": "admin"
    }
  ]
}
```
`/v3/domains` :
```
curl -v -s -X GET -H "X-Auth-Token: "$OS_TOKEN -H "Accept: application/json" -H "Content-Type: application/json" http://xxx.xxx.xxx.xxx:5000/v3/domains\?limit\=500 | jq . 
{
  "domains": [
    {
      "description": "The default domain",
      "links": {
        "self": "http://127.0.0.1:5000/v3/domains/default"
      },
      "tags": [],
      "enabled": true,
      "options": {},
      "id": "default",
      "name": "Default"
    }
  ],
  "links": {
    "self": "http://127.0.0.1:5000/v3/domains?limit=500",
    "previous": null,
    "next": null
  }
}
```

In both results the `options` Field is present.
