### ISSUE TITLE
Create Server - Error 500

### ISSUE THREAD

**Issue by aztromicina** [openstack4j/openstack4j#78]
I'm using the openstack4j lib to create a server, but i get a error 500 when i try to create a server, using a POST request for my endpoint

**my stack:**

Java11
Openstack4j 3.8
spring 3.2.1

**my request:**
POST my api /computers

**My PayLoad:**

```
{
  "domainID": "fdb4d2b73a4b4cacbc9dc80dd9e09eba",
  "flavorID": "1",
  "imageID": "53a9320d-45b9-450b-a7eb-5db06499bffb",
  "networkID": "1e91e20f-1f0d-4141-86c3-0ae8c18ba139",
  "projectID": "string",
  "serverName": "Test",
  "userID": "c0caf80a18334f5caeee8037887f13de"
}
```
**My Method:**

```
 @Api(value="Server Manager")
@RestController
@RequestMapping("/computers")
public class ComputerController {

    @ApiOperation(value = "Create Server")
    @PostMapping
    public String create(@RequestBody ServerRequestDTO serverRequestDTO) {
        OSClientV3 osClientV3 = getOsClientV3();

        User userLoaded = osClientV3.identity().users().get(serverRequestDTO.getUserID());

        Keypair keypair = osClientV3.compute().keypairs().get(userLoaded.getName());

        final ServerCreate serverCreate = osClientV3.compute().servers().serverBuilder()
                .image(serverRequestDTO.getImageID())
                .name(serverRequestDTO.getServerName())
                .flavor(serverRequestDTO.getFlavorID())
                .keypairName(keypair.getName())
                .addSecurityGroup("4f-security-group-cli")
                .networks(Collections.singletonList(serverRequestDTO.getNetworkID()
                ))
                .build();

        Server server = osClientV3.compute().servers().boot(serverCreate);

        return HttpStatus.OK.name();
    }
}

```

**I received this error:**

```
org.openstack4j.api.exceptions.ServerResponseException: Internal Server Error
        at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:86) ~[openstack4j-3.8-withdeps.jar:na]
        at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:96) ~[openstack4j-3.8-withdeps.jar:na]
        at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:92) ~[openstack4j-3.8-withdeps.jar:na]
        at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:51) ~[openstack4j-3.8-withdeps.jar:na]
        at org.openstack4j.connectors.resteasy.HttpResponseImpl.getEntity(HttpResponseImpl.java:64) ~[openstack4j-3.8-withdeps.jar:na]
        at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:215) ~[openstack4j-3.8-withdeps.jar:na]
        at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:205) ~[openstack4j-3.8-withdeps.jar:na]
        at org.openstack4j.openstack.compute.internal.ServerServiceImpl.boot(ServerServiceImpl.java:136) ~[openstack4j-3.8-withdeps.jar:na]
        at com.projeto.openstack.controller.ComputerController.create(ComputerController.java:50) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
        at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```

Can you help me?

**Comment by thiagorouter** [comment]
Hi, I have the same problem about creating the instance of server !

**Comment by olivergondza** [comment]
HTTP 5xx errors means the server failed to handle the request. It is best to turn on the wire logging (specific to the http client you use) and see what is the response body served - it usually contains more information. Also, [latest openstack4j version](https://github.com/openstack4j/openstack4j/issues/72) gives you OpenStack request ID you can forward to OpenStack administrators to have a look at the incident details.

It is unlikely it is library problem or the way you use OpenStack API for server to fail with 5xx code. It might be, but still it would be something OS wants to handle better.

I am closing this as a server problem, please reopen in case there turns out to be something openstack4j can do better here.
