### ISSUE TITLE
Error - SDK Auth - 401 Unauthorized

### ISSUE THREAD

**Issue by aztromicina** [openstack4j/openstack4j#80]
Hi,

I'm using the Openstack4j SDK, and I'm having trouble authenticating myself. I tested all authentication modes, and always 401, can you help me?
I tested it via Curl, Python, and both work, but via SDK java does not work. Can you help me?

SDK Version: com.github.openstack4j.core 3.8

This is my Curl payload and it worked:

```
curl -X POST -H "Content-Type: application/json" \
  -d '
{ "auth": {
    "identity": {
      "methods": ["password"],
      "password": {
        "user": {
          "name": "admin",
          "domain": { "id": "default" },
          "password": "admin1234"
        }
      }
    }
  }
}' \
  "http://xxx.xxx.xxx.xx:5000/v3/auth/tokens" ; echo
```

and return 200 ok

```
{"token": {"methods": ["password"], "user": {"domain": {"id": "default", "name": "Default"}, "id": "aa0ae07d56a04b50
9b02270e991b50b6", "name": "admin", "password_expires_at": null}, "audit_ids": ["vHLMAERxRoWGgRUw_ho-0Q"], "expires_
at": "2020-10-06T17:19:28.000000Z", "issued_at": "2020-10-06T16:19:28.000000Z"}}
```

But My java code don't work, my java code:

```
public class OpenStackAuth {
  public static OSClientV3 getOsClientV3() {
    return OSFactory.builderV3()
      .endpoint("http://xxx.xxx.xxx.xx:5000/v3")
      .credentials("admin", "admin1234", Identifier.byId("default"))
      .scopeToDomain(Identifier.byId("default"))
      .authenticate();
  }
}
```

I also tried this and it didn't work:

```
public class OpenStackAuth {
public static OSClientV3 getOsClientV3() {
    Identifier identifier = Identifier.byName("Default");
    return OSFactory.builderV3()
        .endpoint("http://xxx.xxx.xxx.xx/5000/v3")
        .credentials("admin", "admin1234", identifier)
        .scopeToDomain(identifier)
        .authenticate();
  }
}
```

```
public class OpenStackAuth {
public static OSClientV3 getOsClientV3() {
    Identifier identifier = Identifier.byName("Default");
    return OSFactory.builderV3()
        .endpoint("http://xxx.xxx.xxx.xx/5000/v3")
        .credentials("admin", "admin1234")
        .scopeToDomain(identifier)
        .authenticate();
  }
}
```

```
public class OpenStackAuth {
public static OSClientV3 getOsClientV3() {
    Identifier identifier = Identifier.byId("default");
    return OSFactory.builderV3()
        .endpoint("http://xxx.xxx.xxx.xx/5000/v3")
        .credentials("admin", "admin1234")
        .scopeToDomain(identifier)
        .authenticate();
  }
}
```
User properties in my Openstack Dashboard:

Name: admin
ID: MY_ID
Domain Name: Default
Domain ID: default

Error:

```
`2020-10-06 14:22:59.564 ERROR 3872 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is AuthenticationException{message=Unauthorized, status=401, request=POST http://xxx.xxx.xxx.xx:5000/v3/auth/tokens}] with root cause

org.openstack4j.api.exceptions.AuthenticationException: Unauthorized
	at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:82) ~[openstack4j-3.8-withdeps.jar:na]
ResponseException.java:82
	at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:96) ~[openstack4j-3.8-withdeps.jar:na]
ResponseException.java:96
	at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:92) ~[openstack4j-3.8-withdeps.jar:na]
ResponseException.java:92
	at org.openstack4j.openstack.internal.OSAuthenticator.authenticateV3(OSAuthenticator.java:194) ~[openstack4j-3.8-withdeps.jar:na]
OSAuthenticator.java:194
	at org.openstack4j.openstack.internal.OSAuthenticator.invoke(OSAuthenticator.java:75) ~[openstack4j-3.8-withdeps.jar:na]
OSAuthenticator.java:75
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:172) ~[openstack4j-3.8-withdeps.jar:na]
OSClientBuilder.java:172
	at org.openstack4j.openstack.client.OSClientBuilder$ClientV3.authenticate(OSClientBuilder.java:129) ~[openstack4j-3.8-withdeps.jar:na]
OSClientBuilder.java:129
	at com.project.openstack.util.OpenStackAuth.getOsClientV3(OpenStackAuth.java:16) ~[classes/:na]
OpenStackAuth.java:16`
```

In line 16 of my class contains the authenticated method: .authtenticate();

Can you help me please?

**Comment by olivergondza** [comment]
Here are some tips:

- Try avoiding `.scopeToDomain(identifier)`, you are passing the domain already as third argument to `credentials` method.
- Turn on wire logging (`OSFactory.enableHttpLoggingFilter(true)`) and compare the payload sent by openstack4j.

**Comment by aztromicina** [comment]
> Aqui estão algumas dicas:
> 
> * Tente evitar `.scopeToDomain(identifier)`, você já está passando o domínio como terceiro argumento para o `credentials`método.
> * Ligue o wire logging ( `OSFactory.enableHttpLoggingFilter(true)`) e compare a carga enviada pelo openstack4j.

Hi,
I removed the .scopetoDomain() and am getting a 403 Forbidden.

Here is the code error:

```
2020-10-06 16:56:30.644  INFO 5340 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-10-06 16:56:30.655  INFO 5340 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 11 ms
Data ===================>RegisterDataRequestDTO(registerInfoRequestDTO=RegisterInfoRequestDTO(identifier=123, name=test123, secret=12321, email=123213, isAdmin=false))
2020-10-06 16:56:32.103 ERROR 5340 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is ClientResponseException{message=You are not authorized to perform the requested action: identity:list_domains., status=403, status-code=FORBIDDEN, X-Openstack-Request-Id=req-1304fcdf-9ae6-4e66-8442-000a117eeff4}] with root cause

org.openstack4j.api.exceptions.ClientResponseException: You are not authorized to perform the requested action: identity:list_domains.
	at org.openstack4j.api.exceptions.ResponseException.mapException(ResponseException.java:84) ~[openstack4j-3.8-withdeps.jar:na]
```


Where do I enable wire logging?

My code:

```
public class OpenStackAuth {
public static OSClientV3 getOsClientV3() {
    return OSFactory.builderV3()
        .endpoint("http://xxx.xxx.xxx.xx/5000/v3")
        .credentials("admin", "admin1234", Identifier.byId("default"))
        .authenticate();
  }
}
```

```
@Api(value="Manager Servers")
@RestController
@RequestMapping("/identities")
public class IdentityController {

    @CrossOrigin
    @PostMapping("/users/register")
    public UserDataResponseDTO register(@RequestBody RegisterDataRequestDTO registerDataRequestDTO) {
        System.out.println("Data ===================>" + registerDataRequestDTO);

        Objects.requireNonNull(registerDataRequestDTO, "registerDataRequestDTO must be not null.");

        OSClientV3 osClientV3 = getOsClientV3();

        Domain domain = osClientV3.identity().domains()
                .getByName(registerDataRequestDTO.getRegisterInfoRequestDTO().getIdentifier()).stream()
                .findAny()
                .orElse(null);

        if (Objects.isNull(domain)) {

            domain = osClientV3.identity().domains()
                    .create(Builders.domain().enabled(true)
                            .name(registerDataRequestDTO.getRegisterInfoRequestDTO().getIdentifier())
                            .build());
        }

        Project project = new KeystoneProject().toBuilder().enabled(true).domainId(domain.getId())
                .name(registerDataRequestDTO.getRegisterInfoRequestDTO().getName()).build();

        project = osClientV3.identity().projects().create(project);

        User user = osClientV3.identity().users().create(Builders.user()
                .domainId(domain.getId())
                .name(registerDataRequestDTO.getRegisterInfoRequestDTO().getName())
                .defaultProjectId(project.getId())
                .password(
                        registerDataRequestDTO.getRegisterInfoRequestDTO().getSecret())
                .email(registerDataRequestDTO.getRegisterInfoRequestDTO().getEmail())
                .enabled(true)
                .defaultProjectId(project.getId())
                .build());

        osClientV3.compute().keypairs()
                .create(registerDataRequestDTO.getRegisterInfoRequestDTO().getIdentifier(), null);

        return UserDataResponseDTO.builder().userID(user.getId()).domainID(domain.getId())
                .name(user.getName()).build();
    }

}

```

**Comment by aztromicina** [comment]
I created a proxy to verify my request, in the proxy it returns me a 201, but for my back end, it returns me a 500. Why?

My code:

```
@RestController
@RequestMapping("/auth")
public class OpenStackUtils {

  @GetMapping
  public static OSClientV3 getOsClientV3() {
    return OSFactory
        .builderV3()
        .withConfig(Config.newConfig()
        .withSSLVerificationDisabled()
        .withProxy(new ProxyHost("http://localhost", 9091)))
        .endpoint("http://xxx.xxx.xxx.xx:5000/v3")
        .credentials("admin", "jaisdjadis123AIJ", Identifier.byId("default"))
        .authenticate();
  }

}
```

My Proxy with 201 success:

<img width="938" alt="Captura de Tela 2020-10-06 às 17 59 04" src="https://user-images.githubusercontent.com/71462683/95259620-d402b680-07fd-11eb-9b42-483e79f3c844.png">

My error on code:

`w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.openstack4j.openstack.internal.OSClientSession$OSClientSessionV3["supportedServices"])]`

My error on GET request:
![Uploading Captura de Tela 2020-10-06 às 18.01.45.png…]()

**Comment by olivergondza** [comment]
Call `OSFactory.enableHttpLoggingFilter(true)` to get the wire logging enabled. Note this is specific to http controller, so the log format and even support might vary.
